// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RealtimeDashboardApp.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HealthReportMl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HealthReportMl));
        
        string IMigrationMetadata.Id
        {
            get { return "201506231155334_HealthReport Ml"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
